// Internal difficulty values sent to the backend — display labels are in T[lang].difficultyMap
export const DIFFICULTIES = ['신입', '주니어', '시니어']

export const T = {
  ko: {
    langToggle: 'EN',
    interviewInProgress: '면접이 진행 중입니다. 홈으로 돌아가면 진행 내용이 사라집니다.',
    generatingReport: '종합 리포트를 생성하고 있습니다...',
    reportError: '리포트 생성 중 오류가 발생했습니다: ',
    // LandingPage
    badge: 'AI 면접 준비 도구',
    heroTitle1: '실전처럼 준비하는',
    heroTitle2: '기술 면접 연습',
    heroDesc: '이력서와 채용공고를 분석해 맞춤 질문을 생성하고,\n구조화된 평가 기준으로 답변을 피드백합니다.',
    startInterview: '면접 시작',
    manageDocuments: '문서 관리',
    viewHistory: '기록 보기',
    featuresTitle: '주요 기능',
    features: [
      { title: '이력서 기반 맞춤 질문', desc: '이력서와 JD를 함께 분석해, 지원자의 실제 경험에 근거한 질문을 생성합니다.' },
      { title: '루브릭 기반 채점', desc: 'STAR, 기술 정확성 등 구조화된 평가 기준으로 채점해 일관된 피드백을 제공합니다.' },
      { title: '동적 꼬리질문', desc: '답변 내용을 분석해 추가 확인이 필요한 경우에만 꼬리질문을 생성합니다.' },
    ],
    // JDInput
    back: '이전',
    jdTitle: 'JD 입력',
    jdDesc: '채용공고와 옵션을 입력하면 맞춤 면접 질문을 생성합니다.',
    companyLabel: '회사명',
    companyPlaceholder: '카카오',
    roleLabel: '포지션',
    rolePlaceholder: '백엔드 엔지니어',
    jdLabel: '채용공고 (JD) *',
    jdPlaceholder: 'JD 내용을 붙여넣으세요...',
    difficultyLabel: '난이도',
    difficultyMap: { '신입': '신입', '주니어': '주니어', '시니어': '시니어' },
    questionTypesLabel: '질문 유형',
    questionTypeLabels: { technical: '기술', experience: '경험', culture: '컬처핏' },
    countLabel: '유형별 개수',
    errNoJd: 'JD를 입력해주세요.',
    errNoTypes: '질문 유형을 하나 이상 선택해주세요.',
    errNoQuestion: '질문이 생성되지 않았습니다. 다시 시도해주세요.',
    generating: '질문 생성 중...',
    startBtn: '면접 시작',
    // QuestionCard
    questionOf: (i, total) => `질문 ${i} / ${total}`,
    categoryLabels: { technical: '기술', experience: '경험', culture: '컬처핏' },
    hideHint: '▲ 힌트 숨기기',
    showHint: '▼ 면접관 의도 보기',
    intentLabel: '의도:',
    basisLabel: '근거:',
    answerPlaceholder: '답변을 입력하세요...',
    charCount: (n) => `${n}자`,
    errNoAnswer: '답변을 입력해주세요.',
    evaluating: '평가 중...',
    submit: '제출',
    closeAsk: '▲ 닫기',
    openAsk: '▼ 면접관에게 질문하기',
    askAnswering: '답변 중...',
    askPlaceholder: '면접관에게 궁금한 점을 질문하세요...',
    send: '전송',
    askError: '오류가 발생했습니다.',
    // AnswerFeedback
    scoreTitle: '평가 점수',
    overallLabel: '종합',
    scoreLabels: {
      technical:  ['명확성', '기술 정확성', '깊이'],
      experience: ['명확성', '구체성', '결과'],
      culture:    ['명확성', '진정성', '가치관 적합성'],
    },
    strengths: '강점',
    weaknesses: '개선점',
    modelAnswer: '모범 답안 예시',
    followUpLabel: '꼬리질문',
    followUpPlaceholder: '꼬리질문에 답변하세요...',
    followUpFeedbackLabel: '꼬리질문 피드백',
    followUpEvaluating: '평가 중...',
    followUpSubmit: '답변 제출',
    hideRubric: '채점 근거 숨기기 ↑',
    showRubric: '채점 근거 보기 ↓',
    viewResults: '결과 보기',
    nextQuestion: '다음 질문',
    // HistoryPage
    homeBack: '홈으로',
    historyTitle: '성장 기록',
    historyDesc: '세션을 선택해 점수 추이와 약점 영역을 확인하세요.',
    noSessions: '세션이 없습니다.',
    noCompany: '회사명 없음',
    completed: '완료',
    selectSession: '좌측에서 세션을 선택하세요.',
    loadingHistory: '불러오는 중...',
    lowestPrefix: '종합 점수가 가장 낮은 질문은 ',
    lowestSuffix: (score) => ` (${score}점)입니다. 이 질문 유형을 더 연습해보세요.`,
    overallFeedback: '종합 피드백',
    scoreTrend: '점수 추이',
    colNum: '#',
    colType: '유형',
    colQuestion: '질문',
    colOverall: '종합',
    dateLocale: 'ko-KR',
    // GrowthChart
    catLabels: { technical: '기술', experience: '경험', culture: '컬처핏' },
    chartEmpty: '답변이 2개 이상이어야 그래프를 표시합니다.',
    chartOverallLabel: '종합:',
    chartLineName: '종합 점수',
    // ReportPage
    sessionComplete: '세션 완료',
    questionsAnswered: (n) => `${n}개 질문 답변`,
    avgScore: '평균 종합 점수',
    overallScore: '종합',
    newSession: '새 세션 시작',
    // DocumentUpload
    errPdfOnly: 'PDF 파일만 업로드 가능합니다.',
    errNeedDoc: 'PDF 또는 포트폴리오 텍스트 중 하나는 필요합니다.',
    uploadTitle: '문서 업로드',
    uploadDesc: '이력서와 포트폴리오를 분석해 맞춤 질문 생성에 활용합니다.',
    dropZoneText: '이력서/포트폴리오 PDF를 끌어놓거나 클릭하세요',
    dropZoneHint: '여러 파일 동시 선택 가능',
    portfolioLabel: '포트폴리오 텍스트',
    optional: '(선택)',
    portfolioPlaceholder: 'GitHub 링크, 프로젝트 설명 등을 붙여넣으세요...',
    analysisDone: '분석 완료',
    analyzing: '분석 중...',
    startAnalysis: '분석 시작',
    nextStep: '다음 단계',
    // DocumentsPage
    sourceLabels: { resume: '이력서', portfolio_pdf: '포트폴리오', portfolio: '포트폴리오 텍스트', github: 'GitHub' },
    confirmDeleteDocs: '분석된 문서를 전부 삭제할까요? 다시 업로드해야 합니다.',
    docsTitle: '내 문서',
    docsDesc: '한 번 업로드하면 유지됩니다. 언제든지 추가하거나 초기화할 수 있습니다.',
    noDocsYet: '아직 분석된 문서가 없습니다.',
    addDoc: '문서 추가',
    analyzedDocs: '분석된 문서',
    cancel: '취소',
    deleting: '삭제 중...',
    deleteAll: '전체 삭제',
    // Stepper
    stepUpload: '문서',
    stepInterview: '면접',
    stepDone: '완료',
    // Error fallback
    errGeneric: '오류가 발생했습니다. 다시 시도해주세요.',
  },

  en: {
    langToggle: '한국어',
    interviewInProgress: 'An interview is in progress. Leaving will discard your progress.',
    generatingReport: 'Generating overall report...',
    reportError: 'Error generating report.',
    // LandingPage
    badge: 'AI Interview Coach',
    heroTitle1: 'Practice Tech Interviews',
    heroTitle2: 'Like the Real Thing',
    heroDesc: 'Generates tailored questions from your resume and job description,\nthen provides structured, rubric-based feedback.',
    startInterview: 'Start Interview',
    manageDocuments: 'Manage Documents',
    viewHistory: 'View History',
    featuresTitle: 'Key Features',
    features: [
      { title: 'Resume-Based Questions', desc: 'Analyses your resume and JD together to generate questions grounded in your actual experience.' },
      { title: 'Rubric-Based Scoring', desc: 'Scores answers using structured criteria (STAR, technical accuracy, etc.) for consistent feedback.' },
      { title: 'Dynamic Follow-ups', desc: 'Analyses each answer and only generates a follow-up when deeper exploration is needed.' },
    ],
    // JDInput
    back: 'Back',
    jdTitle: 'Job Description',
    jdDesc: 'Enter the job posting and options to generate tailored interview questions.',
    companyLabel: 'Company',
    companyPlaceholder: 'Google',
    roleLabel: 'Position',
    rolePlaceholder: 'Backend Engineer',
    jdLabel: 'Job Description (JD) *',
    jdPlaceholder: 'Paste the job posting here...',
    difficultyLabel: 'Difficulty',
    difficultyMap: { '신입': 'Entry', '주니어': 'Junior', '시니어': 'Senior' },
    questionTypesLabel: 'Question Types',
    questionTypeLabels: { technical: 'Technical', experience: 'Experience', culture: 'Culture Fit' },
    countLabel: 'Count per Type',
    errNoJd: 'Please enter a job description.',
    errNoTypes: 'Please select at least one question type.',
    errNoQuestion: 'No questions were generated. Please try again.',
    generating: 'Generating questions...',
    startBtn: 'Start Interview',
    // QuestionCard
    questionOf: (i, total) => `Question ${i} / ${total}`,
    categoryLabels: { technical: 'Technical', experience: 'Experience', culture: 'Culture Fit' },
    hideHint: '▲ Hide Hint',
    showHint: '▼ View Interviewer Intent',
    intentLabel: 'Intent:',
    basisLabel: 'Basis:',
    answerPlaceholder: 'Enter your answer...',
    charCount: (n) => `${n} chars`,
    errNoAnswer: 'Please enter your answer.',
    evaluating: 'Evaluating...',
    submit: 'Submit',
    closeAsk: '▲ Close',
    openAsk: '▼ Ask the Interviewer',
    askAnswering: 'Answering...',
    askPlaceholder: 'Ask the interviewer anything...',
    send: 'Send',
    askError: 'An error occurred.',
    // AnswerFeedback
    scoreTitle: 'Scores',
    overallLabel: 'Overall',
    scoreLabels: {
      technical:  ['Clarity', 'Technical Accuracy', 'Depth'],
      experience: ['Clarity', 'Specificity', 'Result'],
      culture:    ['Clarity', 'Authenticity', 'Value Alignment'],
    },
    strengths: 'Strengths',
    weaknesses: 'Areas for Improvement',
    modelAnswer: 'Model Answer',
    followUpLabel: 'Follow-up Question',
    followUpPlaceholder: 'Answer the follow-up question...',
    followUpFeedbackLabel: 'Follow-up Feedback',
    followUpEvaluating: 'Evaluating...',
    followUpSubmit: 'Submit Answer',
    hideRubric: 'Hide Scoring Basis ↑',
    showRubric: 'View Scoring Basis ↓',
    viewResults: 'View Results',
    nextQuestion: 'Next Question',
    // HistoryPage
    homeBack: 'Home',
    historyTitle: 'Growth History',
    historyDesc: 'Select a session to view score trends and weak areas.',
    noSessions: 'No sessions found.',
    noCompany: 'No company',
    completed: 'Completed',
    selectSession: 'Select a session on the left.',
    loadingHistory: 'Loading...',
    lowestPrefix: 'The question with the lowest overall score is ',
    lowestSuffix: (score) => ` (${score}). Practice this question type more.`,
    overallFeedback: 'Overall Feedback',
    scoreTrend: 'Score Trend',
    colNum: '#',
    colType: 'Type',
    colQuestion: 'Question',
    colOverall: 'Overall',
    dateLocale: 'en-US',
    // GrowthChart
    catLabels: { technical: 'Technical', experience: 'Experience', culture: 'Culture Fit' },
    chartEmpty: 'At least 2 answers are needed to display the chart.',
    chartOverallLabel: 'Overall:',
    chartLineName: 'Overall Score',
    // ReportPage
    sessionComplete: 'Session Complete',
    questionsAnswered: (n) => `${n} questions answered`,
    avgScore: 'Average Overall Score',
    overallScore: 'Overall',
    newSession: 'Start New Session',
    // DocumentUpload
    errPdfOnly: 'Only PDF files can be uploaded.',
    errNeedDoc: 'Please provide at least one PDF or portfolio text.',
    uploadTitle: 'Upload Documents',
    uploadDesc: 'Your resume and portfolio will be analysed to generate tailored interview questions.',
    dropZoneText: 'Drag and drop resume/portfolio PDFs here, or click to select',
    dropZoneHint: 'Multiple files can be selected at once',
    portfolioLabel: 'Portfolio Text',
    optional: '(optional)',
    portfolioPlaceholder: 'Paste GitHub links, project descriptions, etc...',
    analysisDone: 'Analysis complete',
    analyzing: 'Analysing...',
    startAnalysis: 'Start Analysis',
    nextStep: 'Next',
    // DocumentsPage
    sourceLabels: { resume: 'Resume', portfolio_pdf: 'Portfolio', portfolio: 'Portfolio Text', github: 'GitHub' },
    confirmDeleteDocs: 'Delete all analysed documents? You will need to re-upload them.',
    docsTitle: 'My Documents',
    docsDesc: 'Uploaded documents are retained. You can add or reset them at any time.',
    noDocsYet: 'No documents have been analysed yet.',
    addDoc: 'Add Document',
    analyzedDocs: 'Analysed Documents',
    cancel: 'Cancel',
    deleting: 'Deleting...',
    deleteAll: 'Delete All',
    // Stepper
    stepUpload: 'Docs',
    stepInterview: 'Interview',
    stepDone: 'Done',
    // Error fallback
    errGeneric: 'An error occurred. Please try again.',
  },
}
